name: Deploy to Firebase

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/frontend/package-lock.json'
    
    - name: Install Frontend Dependencies
      run: |
        cd src/frontend
        npm ci
    
    - name: Install Backend Dependencies
      run: |
        cd src/backend
        npm ci
    
    - name: Build Backend
      run: |
        cd src/backend
        npm run build
    
    - name: Build Frontend
      run: |
        cd src/frontend
        npm run build
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
    
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: drillsargeant-19d36
        channelId: live
    
    - name: Deploy Firebase Functions
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
        gcloud auth activate-service-account --key-file=service-account.json
        npx firebase-tools@latest deploy --only functions --project drillsargeant-19d36 --non-interactive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service-account.json 